name: Generate keymap SVG

on: push

jobs:
  keymap-drawer-export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install keymap-drawer
        run: pip install keymap-drawer

      - name: Generate svg
        run: |
          keymap -c keymap_drawer.config.yaml parse -z config/brain.keymap | keymap -c keymap_drawer.config.yaml draw -d config/boards/shields/brain/brain-layout.dtsi - >docs/export/brain.svg

      - name: Get author and committer info from HEAD commit
        uses: rlespinasse/git-commit-data-action@v1
        if: github.ref == 'refs/heads/master'

      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "CI: Sync draw.io exported files"
          commit_user_name: "${{ env.GIT_COMMIT_COMMITTER_NAME }}"
          commit_user_email: "${{ env.GIT_COMMIT_COMMITTER_EMAIL }}"
          commit_author: "${{ env.GIT_COMMIT_AUTHOR }}"
        if: github.ref == 'refs/heads/master'
